name: Generate movie shows data

# Controls when the workflow will run
on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
   

# Define the jobs that run in this workflow
jobs:
  generate:
    # Specifies the type of runner to use
    runs-on: ubuntu-latest

    # Steps to perform in the job
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Install Google Chrome
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Install ChromeDriver
      # - name: Set up ChromeDriver
      #   run: |
      #     sudo apt-get install -y chromedriver      
          
      # Step 4: Fetch and store show times
      - name: Fetch and store show times
        run: |
          python undetected.py
